version: '3.8'

networks:
  game_network_bridge:
    name: tournament_network_bridge
    driver: bridge

services:
  database-service-mysql:
    image: mysql:8.0
    container_name: mysql-db
    networks:
      - game_network_bridge
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  server-fakhrusy:
    build: ./fakhrusy
    container_name: server-fakhrusy
    networks:
      - game_network_bridge
    command: ./server
    depends_on:
      - database-service-mysql

  client-fakhrusy:
    build: ./fakhrusy
    container_name: client-fakhrusy
    networks:
      - game_network_bridge
    command: sh -c "gcc fakhrusy-c-client.c -o client && ./client"
    depends_on:
      - server-fakhrusy

  server-ariff:
    build: ./ariff
    container_name: server-ariff
    networks:
      - game_network_bridge
    command: ./server
    depends_on:
      - database-service-mysql

  client-ariff:
    build: ./ariff
    container_name: client-ariff
    networks:
      - game_network_bridge
    command: sh -c "gcc ariff-c-client.c -o client && ./client"
    depends_on:
      - server-ariff

  server-adib:
    build: ./adib
    container_name: server-adib
    networks:
      - game_network_bridge
    command: python adib-python-server.py
    depends_on:
      - database-service-mysql

  client-adib:
    build: ./adib
    container_name: client-adib
    networks:
      - game_network_bridge
    command: python adib-python-client.py
    depends_on:
      - server-adib
